"""Session persistence package."""

from .entries import (
    PERSISTED_EVENT_ENVELOPE_SCHEMA_VERSION,
    SESSION_ENTRY_SCHEMA_VERSION,
    ActiveLeafSessionEntry,
    CompactionSessionEntry,
    EventSessionEntry,
    MessageSessionEntry,
    PersistedEventEnvelope,
    SessionEntry,
    SessionInfoSessionEntry,
    SessionTreeEntry,
    ToolResultPresentationSnapshot,
)
from .errors import (
    InvalidSessionBranchPointError,
    MalformedPersistedEventError,
    MalformedSessionEntryError,
    SessionError,
    SessionNavigationCancelledError,
    SessionUnrevertUnavailableError,
    StaleSessionTreeError,
    UnsupportedPersistedEventVersionError,
    UnsupportedSessionEntryVersionError,
)
from .jsonl import (
    JsonlSession,
    JsonlSessionStore,
    SessionForkResult,
    SessionMessagePage,
    SessionNameChange,
    SessionSummary,
    SessionTreeNavigation,
    SessionTreeNodeSummary,
    SessionTreePage,
    SessionTreeUnrevert,
)
from .replay import (
    SessionContextRow,
    SessionReplay,
    SessionReplayError,
    SessionTreeState,
    StaleCompactionError,
    replay_session_entries,
    resolve_session_tree,
)

__all__ = [
    "JsonlSession",
    "JsonlSessionStore",
    "InvalidSessionBranchPointError",
    "PERSISTED_EVENT_ENVELOPE_SCHEMA_VERSION",
    "SESSION_ENTRY_SCHEMA_VERSION",
    "ActiveLeafSessionEntry",
    "CompactionSessionEntry",
    "EventSessionEntry",
    "MalformedPersistedEventError",
    "MalformedSessionEntryError",
    "MessageSessionEntry",
    "PersistedEventEnvelope",
    "SessionContextRow",
    "SessionEntry",
    "SessionError",
    "SessionForkResult",
    "SessionMessagePage",
    "SessionInfoSessionEntry",
    "SessionNameChange",
    "SessionNavigationCancelledError",
    "SessionUnrevertUnavailableError",
    "SessionReplay",
    "SessionReplayError",
    "SessionSummary",
    "SessionTreeEntry",
    "SessionTreeNavigation",
    "SessionTreeNodeSummary",
    "SessionTreeUnrevert",
    "SessionTreePage",
    "SessionTreeState",
    "StaleCompactionError",
    "StaleSessionTreeError",
    "ToolResultPresentationSnapshot",
    "UnsupportedPersistedEventVersionError",
    "UnsupportedSessionEntryVersionError",
    "replay_session_entries",
    "resolve_session_tree",
]
