//! Generated Serde models for Wisp's current live JSONL-RPC protocol.
//!
//! Python models and the committed JSON Schemas are the semantic source of
//! truth. The modules below are generated by `typify` at compile time and must
//! not be replaced with handwritten wire structs.

#![forbid(unsafe_code)]

use serde::de::DeserializeOwned;
use serde_json::Value;
use std::fmt;
use std::sync::LazyLock;

#[derive(Debug)]
pub struct ProtocolDecodeError(String);

impl fmt::Display for ProtocolDecodeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for ProtocolDecodeError {}

struct SchemaContract {
    schema: Value,
    validator: jsonschema::Validator,
}

impl SchemaContract {
    fn new(schema: &str) -> Self {
        let schema: Value = serde_json::from_str(schema).expect("embedded RPC schema must be JSON");
        let validator = jsonschema::draft202012::new(&schema)
            .expect("embedded RPC schema must be valid Draft 2020-12");
        Self { schema, validator }
    }
}

static COMMAND_CONTRACT: LazyLock<SchemaContract> = LazyLock::new(|| {
    SchemaContract::new(include_str!(
        "../../../schemas/live-rpc/v2/commands.schema.json"
    ))
});
static EVENT_CONTRACT: LazyLock<SchemaContract> = LazyLock::new(|| {
    SchemaContract::new(include_str!(
        "../../../schemas/live-rpc/v2/events.schema.json"
    ))
});

fn deserialize_known<T>(contract: &SchemaContract, value: Value) -> Result<T, ProtocolDecodeError>
where
    T: DeserializeOwned,
{
    let discriminator = value
        .get("type")
        .and_then(Value::as_str)
        .ok_or_else(|| ProtocolDecodeError("RPC value has no string discriminator".into()))?;
    let known = contract.schema["discriminator"]["mapping"]
        .as_object()
        .is_some_and(|mapping| mapping.contains_key(discriminator));
    if !known {
        return Err(ProtocolDecodeError(format!(
            "unknown RPC discriminator: {discriminator}"
        )));
    }
    contract
        .validator
        .validate(&value)
        .map_err(|_| ProtocolDecodeError("RPC value violates the canonical schema".into()))?;
    serde_json::from_value(value)
        .map_err(|error| ProtocolDecodeError(format!("invalid RPC value: {error}")))
}

pub mod handshake_request {
    typify::import_types!(schema = "../../schemas/live-rpc/v2/client-handshake.schema.json");
}

pub mod handshake_response {
    typify::import_types!(schema = "../../schemas/live-rpc/v2/server-handshake.schema.json");
}

pub mod commands {
    typify::import_types!(schema = "../../schemas/live-rpc/v2/rust-commands.schema.json");

    pub fn deserialize(
        value: serde_json::Value,
    ) -> Result<WispTypedClientRpcCommands, super::ProtocolDecodeError> {
        super::deserialize_known(&super::COMMAND_CONTRACT, value)
    }
}

pub mod events {
    typify::import_types!(schema = "../../schemas/live-rpc/v2/rust-events.schema.json");

    pub fn deserialize(
        value: serde_json::Value,
    ) -> Result<WispCurrentLiveEventOutput, super::ProtocolDecodeError> {
        super::deserialize_known(&super::EVENT_CONTRACT, value)
    }
}
