//! Validated Serde models for Wisp's current live JSONL-RPC protocol.
//!
//! Python models and the committed JSON Schemas are the semantic source of
//! truth. Private wire projections are generated by `typify` at compile time;
//! public types wrap them so every deserialization path enforces the canonical
//! schema and its cross-field invariants.

#![forbid(unsafe_code)]

use serde::de::DeserializeOwned;
use serde_json::Value;
use std::fmt;
use std::sync::LazyLock;

/// The canonical manifest embedded alongside the generated live RPC v2 models.
pub const LIVE_RPC_MANIFEST_JSON: &str = include_str!("../../../schemas/live-rpc/v2/manifest.json");
/// The only live RPC protocol version implemented by these models.
pub const LIVE_RPC_PROTOCOL_VERSION: u32 = 2;
/// The current Wisp event schema version.
pub const EVENT_SCHEMA_VERSION: u32 = 34;
/// The fixed maximum payload size for either handshake frame.
pub const HANDSHAKE_FRAME_BYTES: usize = 64 * 1024;
/// The schema-level ceiling for negotiated application frames.
pub const MAX_APPLICATION_FRAME_BYTES: usize = 64 * 1024 * 1024;

#[derive(Debug)]
pub struct ProtocolDecodeError(String);

impl fmt::Display for ProtocolDecodeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl std::error::Error for ProtocolDecodeError {}

struct StrictJsonValue(Value);

impl<'de> serde::Deserialize<'de> for StrictJsonValue {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        struct StrictValueVisitor;

        impl<'de> serde::de::Visitor<'de> for StrictValueVisitor {
            type Value = StrictJsonValue;

            fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str("a JSON value without duplicate object fields")
            }

            fn visit_bool<E>(self, value: bool) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::Bool(value)))
            }

            fn visit_i64<E>(self, value: i64) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::Number(value.into())))
            }

            fn visit_u64<E>(self, value: u64) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::Number(value.into())))
            }

            fn visit_f64<E>(self, value: f64) -> Result<Self::Value, E>
            where
                E: serde::de::Error,
            {
                serde_json::Number::from_f64(value)
                    .map(Value::Number)
                    .map(StrictJsonValue)
                    .ok_or_else(|| E::custom("non-finite JSON number"))
            }

            fn visit_str<E>(self, value: &str) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::String(value.into())))
            }

            fn visit_string<E>(self, value: String) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::String(value)))
            }

            fn visit_none<E>(self) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::Null))
            }

            fn visit_unit<E>(self) -> Result<Self::Value, E> {
                Ok(StrictJsonValue(Value::Null))
            }

            fn visit_some<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                <StrictJsonValue as serde::Deserialize>::deserialize(deserializer)
            }

            fn visit_seq<A>(self, mut sequence: A) -> Result<Self::Value, A::Error>
            where
                A: serde::de::SeqAccess<'de>,
            {
                let mut values = Vec::new();
                while let Some(StrictJsonValue(value)) = sequence.next_element()? {
                    values.push(value);
                }
                Ok(StrictJsonValue(Value::Array(values)))
            }

            fn visit_map<A>(self, mut object: A) -> Result<Self::Value, A::Error>
            where
                A: serde::de::MapAccess<'de>,
            {
                let mut values = serde_json::Map::new();
                while let Some(key) = object.next_key::<String>()? {
                    if values.contains_key(&key) {
                        return Err(serde::de::Error::custom(format!(
                            "duplicate JSON object field: {key}"
                        )));
                    }
                    let StrictJsonValue(value) = object.next_value()?;
                    values.insert(key, value);
                }
                Ok(StrictJsonValue(Value::Object(values)))
            }
        }

        deserializer.deserialize_any(StrictValueVisitor)
    }
}

struct SchemaContract {
    schema: Value,
    validator: jsonschema::Validator,
}

impl SchemaContract {
    fn new(schema: &str) -> Self {
        let schema: Value = serde_json::from_str(schema).expect("embedded RPC schema must be JSON");
        let validator = jsonschema::draft202012::new(&schema)
            .expect("embedded RPC schema must be valid Draft 2020-12");
        Self { schema, validator }
    }

    fn validate(&self, value: &Value) -> Result<(), ProtocolDecodeError> {
        self.validator
            .validate(value)
            .map_err(|_| ProtocolDecodeError("RPC value violates the canonical schema".into()))?;
        validate_cross_field_invariants(&self.schema, value)
    }
}

static HANDSHAKE_REQUEST_CONTRACT: LazyLock<SchemaContract> = LazyLock::new(|| {
    SchemaContract::new(include_str!(
        "../../../schemas/live-rpc/v2/client-handshake.schema.json"
    ))
});
static HANDSHAKE_RESPONSE_CONTRACT: LazyLock<SchemaContract> = LazyLock::new(|| {
    SchemaContract::new(include_str!(
        "../../../schemas/live-rpc/v2/server-handshake.schema.json"
    ))
});
static COMMAND_CONTRACT: LazyLock<SchemaContract> = LazyLock::new(|| {
    SchemaContract::new(include_str!(
        "../../../schemas/live-rpc/v2/commands.schema.json"
    ))
});
static EVENT_CONTRACT: LazyLock<SchemaContract> = LazyLock::new(|| {
    SchemaContract::new(include_str!(
        "../../../schemas/live-rpc/v2/events.schema.json"
    ))
});

fn validate_cross_field_invariants(
    schema: &Value,
    value: &Value,
) -> Result<(), ProtocolDecodeError> {
    let selected_schema = value
        .get("type")
        .and_then(Value::as_str)
        .and_then(|discriminator| schema["discriminator"]["mapping"][discriminator].as_str())
        .and_then(|reference| reference.strip_prefix("#/$defs/"))
        .and_then(|definition| schema["$defs"].get(definition))
        .unwrap_or(schema);
    validate_invariant_list(selected_schema, value)?;

    if value.get("type").and_then(Value::as_str) == Some("rpc.commands") {
        let descriptor_schema = &schema["$defs"]["RpcCommandDescriptor"];
        let descriptors = value["commands"].as_array().ok_or_else(|| {
            ProtocolDecodeError("RPC command report has no descriptor array".into())
        })?;
        for descriptor in descriptors {
            validate_invariant_list(descriptor_schema, descriptor)?;
        }
    }
    Ok(())
}

fn validate_invariant_list(schema: &Value, value: &Value) -> Result<(), ProtocolDecodeError> {
    let Some(invariants) = schema["x-wisp-cross-field-invariants"].as_array() else {
        return Ok(());
    };

    for invariant in invariants {
        let valid = match invariant["kind"].as_str() {
            Some("ordered-range") => {
                let minimum = invariant["minimum_property"].as_str();
                let maximum = invariant["maximum_property"].as_str();
                match (minimum, maximum) {
                    (Some(minimum), Some(maximum)) => value[minimum]
                        .as_u64()
                        .zip(value[maximum].as_u64())
                        .is_some_and(|(minimum, maximum)| minimum <= maximum),
                    _ => false,
                }
            }
            Some("value-in-range") => {
                let minimum = invariant["minimum_property"].as_str();
                let maximum = invariant["maximum_property"].as_str();
                let selected = invariant["value_property"].as_str();
                match (minimum, maximum, selected) {
                    (Some(minimum), Some(maximum), Some(selected)) => value[minimum]
                        .as_u64()
                        .zip(value[maximum].as_u64())
                        .zip(value[selected].as_u64())
                        .is_some_and(|((minimum, maximum), selected)| {
                            minimum <= selected && selected <= maximum
                        }),
                    _ => false,
                }
            }
            Some("array-subset") => {
                let subset = invariant["subset_property"].as_str();
                let superset = invariant["superset_property"].as_str();
                match (subset, superset) {
                    (Some(subset), Some(superset)) => value[subset]
                        .as_array()
                        .zip(value[superset].as_array())
                        .is_some_and(|(subset, superset)| {
                            subset.iter().all(|member| superset.contains(member))
                        }),
                    _ => false,
                }
            }
            Some("properties-not-equal") => {
                let left = invariant["left_property"].as_str();
                let right = invariant["right_property"].as_str();
                match (left, right) {
                    (Some(left), Some(right)) => value.get(left) != value.get(right),
                    _ => false,
                }
            }
            Some("value-equals-prefixed-property") => {
                let prefix = invariant["prefix"].as_str();
                let source = invariant["source_property"].as_str();
                let target = invariant["value_property"].as_str();
                match (prefix, source, target) {
                    (Some(prefix), Some(source), Some(target)) => value[source]
                        .as_str()
                        .zip(value[target].as_str())
                        .is_some_and(|(source, target)| format!("{prefix}{source}") == target),
                    _ => false,
                }
            }
            Some("boolean-reports-property-change") => {
                let reported = invariant["boolean_property"].as_str();
                let previous = invariant["previous_property"].as_str();
                let current = invariant["current_property"].as_str();
                match (reported, previous, current) {
                    (Some(reported), Some(previous), Some(current)) => value[reported]
                        .as_bool()
                        .is_some_and(|reported| reported == (value[previous] != value[current])),
                    _ => false,
                }
            }
            Some("array-length-at-most-property") => {
                let array = invariant["array_property"].as_str();
                let maximum = invariant["maximum_property"].as_str();
                match (array, maximum) {
                    (Some(array), Some(maximum)) => value[array]
                        .as_array()
                        .zip(value[maximum].as_u64())
                        .is_some_and(|(array, maximum)| array.len() as u64 <= maximum),
                    _ => false,
                }
            }
            Some("array-item-property-unique") => {
                let array = invariant["array_property"].as_str();
                let item_property = invariant["item_property"].as_str();
                match (array, item_property) {
                    (Some(array), Some(item_property)) => {
                        value[array].as_array().is_some_and(|array| {
                            let mut observed = std::collections::BTreeSet::new();
                            array.iter().all(|item| {
                                item[item_property]
                                    .as_str()
                                    .is_some_and(|member| observed.insert(member))
                            })
                        })
                    }
                    _ => false,
                }
            }
            Some("value-equals-last-array-item-property") => {
                let when = invariant["when_property"].as_str();
                let array = invariant["array_property"].as_str();
                let item_property = invariant["item_property"].as_str();
                let target = invariant["value_property"].as_str();
                match (when, array, item_property, target) {
                    (Some(when), Some(array), Some(item_property), Some(target)) => {
                        value[when].as_bool().is_some_and(|enabled| {
                            !enabled
                                || value[array]
                                    .as_array()
                                    .and_then(|items| items.last())
                                    .is_some_and(|item| value[target] == item[item_property])
                        })
                    }
                    _ => false,
                }
            }
            _ => false,
        };
        if !valid {
            return Err(ProtocolDecodeError(
                "RPC value violates a canonical cross-field invariant".into(),
            ));
        }
    }
    Ok(())
}

fn deserialize_contract<T>(
    contract: &SchemaContract,
    value: Value,
) -> Result<T, ProtocolDecodeError>
where
    T: DeserializeOwned,
{
    contract.validate(&value)?;
    serde_json::from_value(value)
        .map_err(|error| ProtocolDecodeError(format!("invalid RPC value: {error}")))
}

fn deserialize_known<T>(contract: &SchemaContract, value: Value) -> Result<T, ProtocolDecodeError>
where
    T: DeserializeOwned,
{
    let discriminator = value
        .get("type")
        .and_then(Value::as_str)
        .ok_or_else(|| ProtocolDecodeError("RPC value has no string discriminator".into()))?;
    let known = contract.schema["discriminator"]["mapping"]
        .as_object()
        .is_some_and(|mapping| mapping.contains_key(discriminator));
    if !known {
        return Err(ProtocolDecodeError(format!(
            "unknown RPC discriminator: {discriminator}"
        )));
    }
    deserialize_contract(contract, value)
}

macro_rules! validated_wire_wrapper {
    ($wrapper:ident, $inner:ty) => {
        #[derive(Clone, Debug, serde::Serialize)]
        #[serde(transparent)]
        pub struct $wrapper($inner);

        impl $wrapper {
            /// Serialize this validated protocol value for transport or inspection.
            pub fn to_value(&self) -> Result<serde_json::Value, serde_json::Error> {
                serde_json::to_value(self)
            }

            /// Consume this validated protocol value and return its JSON representation.
            pub fn into_value(self) -> Result<serde_json::Value, serde_json::Error> {
                serde_json::to_value(self)
            }
        }

        impl TryFrom<serde_json::Value> for $wrapper {
            type Error = $crate::ProtocolDecodeError;

            fn try_from(value: serde_json::Value) -> Result<Self, Self::Error> {
                deserialize(value)
            }
        }

        impl<'de> serde::Deserialize<'de> for $wrapper {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::Deserializer<'de>,
            {
                let $crate::StrictJsonValue(value) =
                    <$crate::StrictJsonValue as serde::Deserialize>::deserialize(deserializer)?;
                deserialize(value).map_err(serde::de::Error::custom)
            }
        }
    };
}

pub mod handshake_request {
    mod generated {
        typify::import_types!(schema = "../../schemas/live-rpc/v2/client-handshake.schema.json");
    }

    validated_wire_wrapper!(RpcHandshakeRequest, generated::RpcHandshakeRequest);

    impl RpcHandshakeRequest {
        /// Construct the frontend's current, capability-free live RPC request.
        pub fn current(
            frontend_name: &str,
            frontend_version: &str,
        ) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "rpc.handshake.request",
                "frontend_name": frontend_name,
                "frontend_version": frontend_version,
                "min_protocol_version": super::LIVE_RPC_PROTOCOL_VERSION,
                "max_protocol_version": super::LIVE_RPC_PROTOCOL_VERSION,
                "min_event_schema_version": super::EVENT_SCHEMA_VERSION,
                "max_event_schema_version": super::EVENT_SCHEMA_VERSION,
                "supported_capabilities": [],
                "required_capabilities": []
            }))
        }
    }

    pub fn deserialize(
        value: serde_json::Value,
    ) -> Result<RpcHandshakeRequest, super::ProtocolDecodeError> {
        super::deserialize_contract(&super::HANDSHAKE_REQUEST_CONTRACT, value)
            .map(RpcHandshakeRequest)
    }
}

pub mod handshake_response {
    mod generated {
        typify::import_types!(schema = "../../schemas/live-rpc/v2/server-handshake.schema.json");
    }

    validated_wire_wrapper!(RpcHandshakeResponse, generated::RpcHandshakeResponse);

    impl RpcHandshakeResponse {
        fn wire_value(&self) -> serde_json::Value {
            serde_json::to_value(&self.0)
                .expect("validated generated handshake values must serialize")
        }

        /// Return the backend package version reported by either outcome.
        pub fn backend_package_version(&self) -> String {
            self.wire_value()["backend_package_version"]
                .as_str()
                .expect("validated handshake has a backend package version")
                .to_owned()
        }

        /// Return the backend's safe rejection code and message, if rejected.
        pub fn rejection(&self) -> Option<(String, String)> {
            let value = self.wire_value();
            (value["type"] == "rpc.handshake.rejected").then(|| {
                (
                    value["code"]
                        .as_str()
                        .expect("validated rejection has a code")
                        .to_owned(),
                    value["message"]
                        .as_str()
                        .expect("validated rejection has a message")
                        .to_owned(),
                )
            })
        }

        /// Return selected protocol, event schema, and directional limits on acceptance.
        pub fn accepted_contract(&self) -> Option<(u32, u32, usize, usize)> {
            let value = self.wire_value();
            (value["type"] == "rpc.handshake.accepted").then(|| {
                (
                    value["protocol_version"].as_u64().unwrap() as u32,
                    value["event_schema_version"].as_u64().unwrap() as u32,
                    value["limits"]["max_client_frame_bytes"].as_u64().unwrap() as usize,
                    value["limits"]["max_server_frame_bytes"].as_u64().unwrap() as usize,
                )
            })
        }
    }

    pub fn deserialize(
        value: serde_json::Value,
    ) -> Result<RpcHandshakeResponse, super::ProtocolDecodeError> {
        super::deserialize_known(&super::HANDSHAKE_RESPONSE_CONTRACT, value)
            .map(RpcHandshakeResponse)
    }
}

pub mod commands {
    mod generated {
        typify::import_types!(schema = "../../schemas/live-rpc/v2/rust-commands.schema.json");
    }

    validated_wire_wrapper!(
        WispTypedClientRpcCommands,
        generated::WispTypedClientRpcCommands
    );

    /// Lifetime granted by an approved tool request.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum ApprovalScope {
        Once,
        ToolSession,
        AllSession,
    }

    /// One active agent queue addressed by the live RPC protocol.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum QueueKind {
        Steering,
        FollowUp,
    }

    impl QueueKind {
        /// Return the canonical live-RPC wire value.
        pub const fn as_wire_value(self) -> &'static str {
            match self {
                Self::Steering => "steering",
                Self::FollowUp => "follow_up",
            }
        }
    }

    impl ApprovalScope {
        fn as_wire_value(self) -> &'static str {
            match self {
                Self::Once => "once",
                Self::ToolSession => "tool_session",
                Self::AllSession => "all_session",
            }
        }
    }

    impl WispTypedClientRpcCommands {
        /// Construct one agent-turn request.
        pub fn prompt(id: &str, prompt: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "prompt", "id": id, "prompt": prompt}))
        }

        /// Queue text after the active run's current assistant/tool batch.
        pub fn steer(id: &str, content: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "steer", "id": id, "content": content}))
        }

        /// Queue text for when the active run would otherwise stop.
        pub fn follow_up(id: &str, content: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "follow_up", "id": id, "content": content}))
        }

        /// Construct a response to one pending tool approval request.
        pub fn approval(
            id: &str,
            call_id: &str,
            approved: bool,
            reason: Option<&str>,
            scope: Option<ApprovalScope>,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "approval",
                "id": id,
                "call_id": call_id,
                "approved": approved,
            });
            let object = value
                .as_object_mut()
                .expect("command constructors create JSON objects");
            if let Some(reason) = reason {
                object.insert("reason".into(), serde_json::Value::String(reason.into()));
            }
            if let Some(scope) = scope {
                object.insert(
                    "scope".into(),
                    serde_json::Value::String(scope.as_wire_value().into()),
                );
            }
            deserialize(value)
        }

        /// Construct a request for the active session's usage snapshot.
        pub fn get_session_stats(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "get_session_stats", "id": id}))
        }

        /// Construct a bounded persisted-session catalog request.
        pub fn get_sessions(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "get_sessions", "id": id, "limit": 50}))
        }

        /// Construct a request to deselect the active session.
        pub fn new_session(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "new_session", "id": id}))
        }

        /// Construct a request to select one persisted session.
        pub fn select_session(
            id: &str,
            session_id: &str,
        ) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "select_session",
                "id": id,
                "session_id": session_id,
            }))
        }

        /// Construct one bounded latest-page history request.
        pub fn get_messages(
            id: &str,
            session_id: Option<&str>,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "get_messages",
                "id": id,
                "limit": 200,
                "complete_structure": true,
                "full_content": false,
            });
            if let Some(session_id) = session_id {
                value
                    .as_object_mut()
                    .expect("command constructors create JSON objects")
                    .insert(
                        "session_id".into(),
                        serde_json::Value::String(session_id.into()),
                    );
            }
            deserialize(value)
        }

        /// Construct one bounded older-page history request.
        pub fn get_messages_older(
            id: &str,
            session_id: Option<&str>,
            before_entry_id: &str,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "get_messages",
                "id": id,
                "limit": 75,
                "before_entry_id": before_entry_id,
                "complete_structure": true,
                "full_content": false,
                "allow_during_prompt": true,
            });
            if let Some(session_id) = session_id {
                value
                    .as_object_mut()
                    .expect("command constructors create JSON objects")
                    .insert(
                        "session_id".into(),
                        serde_json::Value::String(session_id.into()),
                    );
            }
            deserialize(value)
        }

        /// Construct one bounded newer-page history request.
        pub fn get_messages_newer(
            id: &str,
            session_id: Option<&str>,
            after_entry_id: &str,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "get_messages",
                "id": id,
                "limit": 75,
                "after_entry_id": after_entry_id,
                "complete_structure": true,
                "full_content": false,
                "allow_during_prompt": true,
            });
            if let Some(session_id) = session_id {
                value
                    .as_object_mut()
                    .expect("command constructors create JSON objects")
                    .insert(
                        "session_id".into(),
                        serde_json::Value::String(session_id.into()),
                    );
            }
            deserialize(value)
        }

        /// Construct one exact persisted-message fetch for an on-demand detail view.
        pub fn get_message_detail(
            id: &str,
            session_id: Option<&str>,
            entry_id: &str,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "get_messages",
                "id": id,
                "limit": 1,
                "entry_ids": [entry_id],
                "complete_structure": true,
                "full_content": true,
                "allow_during_prompt": true,
            });
            if let Some(session_id) = session_id {
                value
                    .as_object_mut()
                    .expect("command constructors create JSON objects")
                    .insert(
                        "session_id".into(),
                        serde_json::Value::String(session_id.into()),
                    );
            }
            deserialize(value)
        }

        /// Set or clear the selected session's display name.
        pub fn set_session_name(id: &str, name: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "set_session_name",
                "id": id,
                "name": name,
            }))
        }

        /// Clone the selected session's active path and select the clone.
        pub fn clone_session(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "clone_session", "id": id}))
        }

        /// Fork before one persisted user message and select the fork.
        pub fn fork_session(id: &str, entry_id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "fork_session",
                "id": id,
                "entry_id": entry_id,
            }))
        }

        /// Request one bounded append-ordered page of the selected session tree.
        pub fn get_session_tree(
            id: &str,
            after_entry_id: Option<&str>,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "get_session_tree",
                "id": id,
                "limit": 200,
            });
            if let Some(after_entry_id) = after_entry_id {
                value
                    .as_object_mut()
                    .expect("command constructors create JSON objects")
                    .insert(
                        "after_entry_id".into(),
                        serde_json::Value::String(after_entry_id.into()),
                    );
            }
            deserialize(value)
        }

        /// Navigate the selected session tree to one persisted entry.
        pub fn navigate_session_tree(
            id: &str,
            entry_id: &str,
        ) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "navigate_session_tree",
                "id": id,
                "entry_id": entry_id,
            }))
        }

        /// Reverse the selected session's latest explicit tree navigation.
        pub fn unrevert_session_tree(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "unrevert_session_tree",
                "id": id,
            }))
        }

        /// Construct a request to cancel a running or queued command.
        pub fn cancel(id: &str, target_id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "cancel", "id": id, "target_id": target_id}))
        }

        /// Request the active or retained queue state.
        pub fn get_queue_state(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "get_queue_state", "id": id}))
        }

        /// Remove the latest item from one active queue.
        pub fn pop_queue(id: &str, kind: QueueKind) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({
                "type": "pop_queue",
                "id": id,
                "kind": kind.as_wire_value(),
            }))
        }

        /// Construct a response to one pending project-trust request.
        pub fn trust(
            id: &str,
            request_id: &str,
            trusted: bool,
            reason: Option<&str>,
            transient: Option<bool>,
        ) -> Result<Self, super::ProtocolDecodeError> {
            let mut value = serde_json::json!({
                "type": "trust",
                "id": id,
                "request_id": request_id,
                "trusted": trusted,
            });
            let object = value
                .as_object_mut()
                .expect("command constructors create JSON objects");
            if let Some(reason) = reason {
                object.insert("reason".into(), serde_json::Value::String(reason.into()));
            }
            if let Some(transient) = transient {
                object.insert("transient".into(), serde_json::Value::Bool(transient));
            }
            deserialize(value)
        }

        /// Construct the typed command used to request graceful backend shutdown.
        pub fn shutdown(id: &str) -> Result<Self, super::ProtocolDecodeError> {
            deserialize(serde_json::json!({"type": "shutdown", "id": id}))
        }
    }

    pub fn deserialize(
        value: serde_json::Value,
    ) -> Result<WispTypedClientRpcCommands, super::ProtocolDecodeError> {
        super::deserialize_known(&super::COMMAND_CONTRACT, value).map(WispTypedClientRpcCommands)
    }
}

pub mod events {
    mod generated {
        typify::import_types!(schema = "../../schemas/live-rpc/v2/rust-events.schema.json");
    }

    validated_wire_wrapper!(
        WispCurrentLiveEventOutput,
        generated::WispCurrentLiveEventOutput
    );

    /// Terminal result projected from a validated `rpc.command.finished` event.
    #[derive(Clone, Debug, Eq, PartialEq)]
    pub enum CommandFinishedOutcome {
        Succeeded,
        Failed { error: Option<String> },
    }

    impl WispCurrentLiveEventOutput {
        fn wire_value(&self) -> serde_json::Value {
            serde_json::to_value(&self.0).expect("validated generated events must serialize")
        }

        /// Return the stable event discriminator for diagnostic display.
        pub fn event_type(&self) -> String {
            self.wire_value()["type"]
                .as_str()
                .expect("validated event has a discriminator")
                .to_owned()
        }

        /// Return the validated event schema version carried by this event.
        pub fn schema_version(&self) -> u32 {
            self.wire_value()["schema_version"]
                .as_u64()
                .expect("validated event has a schema version") as u32
        }

        /// Project the terminal outcome for one exact command, if this is its event.
        pub fn command_finished_outcome(
            &self,
            id: &str,
            command_type: &str,
        ) -> Option<CommandFinishedOutcome> {
            let value = self.wire_value();
            if value["type"] != "rpc.command.finished"
                || value["command_id"] != id
                || value["command_type"] != command_type
            {
                return None;
            }
            Some(if value["ok"] == true {
                CommandFinishedOutcome::Succeeded
            } else {
                CommandFinishedOutcome::Failed {
                    error: value["error"].as_str().map(str::to_owned),
                }
            })
        }

        /// Check for the successful terminal event of one typed command.
        pub fn successful_command_finished(&self, id: &str, command_type: &str) -> bool {
            self.command_finished_outcome(id, command_type)
                == Some(CommandFinishedOutcome::Succeeded)
        }
    }

    pub fn deserialize(
        value: serde_json::Value,
    ) -> Result<WispCurrentLiveEventOutput, super::ProtocolDecodeError> {
        super::deserialize_known(&super::EVENT_CONTRACT, value).map(WispCurrentLiveEventOutput)
    }
}
