[package]
name = "wisp-python"
version = "0.2.0-rc.2"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["abi3-py312", "extension-module"] }
wisp-process-text = { path = "../wisp-process-text" }
wisp-search = { path = "../wisp-search" }

[build-dependencies]
pyo3-build-config.workspace = true
